#ifndef Constants_h
#define Constants_h

#define PWM_GENERATOR_FREQUENCY 54

#define DRIVE_SIZE 3.25
#define DRIVE_VECTOR_SCALE 0.707

//Launcher Joint Limits
#define LAUNCHER_MAX_RPM 3200
#define LAUNCHER_MIN_RPM 0
#define LAUNCHER_SENSOR_SCALE 15000
#define LAUNCHER_MIN 0
#define LAUNCHER_MAX 4095
#define LAUNCHER_CENTER 2048
#define LAUNCHER_JOINT_CENTER 1600

//Drive joint limits
#define DRIVE_MAX_RPM 168
#define DRIVE_MIN_RPM -168
#define DRIVE_MIN_OUTPUT 268
#define DRIVE_MAX_OUTPUT 355
#define DRIVE_ZERO_CENTER 312
#define DRIVE_ZERO_DEADBAND_RANGE 4

#define DRIVE_FRONT_LEFT_SENSOR_SCALE 170
#define DRIVE_FRONT_RIGHT_SENSOR_SCALE 170
#define DRIVE_BACK_LEFT_SENSOR_SCALE 170
#define DRIVE_BACK_RIGHT_SENSOR_SCALE 170
// Comm limits
#define COMMUNICATION_TIMEOUT_MILLIS 250
#define WRITE_COMM_TIMEOUT_MILLIS 100

#endif