#ifndef PinDeclarations_h
#define PinDeclarations_h

#define BLUETOOTH_TX 0
#define BLUETOOTH_RX 1

#define SERVO_ENABLE_PIN 4
#define DEBUG_PIN 2
#define SERVO_LOGIC_ENABLE A3

#define FRONT_LEFT_WHEEL_EXPANSION_CHANNEL 1
#define BACK_LEFT_WHEEL_EXPANSION_CHANNEL 2
#define BACK_RIGHT_WHEEL_EXPANSION_CHANNEL 9
#define FRONT_RIGHT_WHEEL_EXPANSION_CHANNEL 10

#define BACK_RIGHT_WHEEL_FEEDBACK_PIN 5
#define FRONT_RIGHT_WHEEL_FEEDBACK_PIN 6
#define BACK_LEFT_WHEEL_FEEDBACK_PIN 7
#define FRONT_LEFT_WHEEL_FEEDBACK_PIN 8

#define FLYWHEEL_EXPANSION_CHANNEL_A 14
#define FLYWHEEL_EXPANSION_CHANNEL_B 15
#define FLYWHEEL_FEEDBACK_CHANNEL_A 9
#define FLYWHEEL_FEEDBACK_CHANNEL_B 10

#define INTAKE_SERVO_EXPANSION_CHANNEL 0   // LEFT
#define INTAKE_SERVO2_EXPANSION_CHANNEL 11 // RIGHT
#define INTAKE_LIMIT_SWITCH_PIN A0

#endif
