#ifndef PinDeclarations_h
#define PinDeclarations_h

    #define FRONT_LEFT_WHEEL_EXPANSION_CHANNEL 0
    #define FRONT_RIGHT_WHEEL_EXPANSION_CHANNEL 1
    #define BACK_LEFT_WHEEL_EXPANSION_CHANNEL 2
    #define BACK_RIGHT_WHEEL_EXPANSION_CHANNEL 3

    #define FRONT_LEFT_WHEEL_FEEDBACK_PIN 0
    #define FRONT_RIGHT_WHEEL_FEEDBACK_PIN 1
    #define BACK_LEFT_WHEEL_FEEDBACK_PIN 2
    #define BACK_RIGHT_WHEEL_FEEDBACK_PIN 3

    #define FLYWHEEL_EXPANSION_CHANNEL 4
    #define FLYWHEEL_FEEDBACK_CHANNEL_A 4
    #define FLYWHEEL_FEEDBACK_CHANNEL_B 5
    
    #define INTAKE_SERVO_EXPANSION_CHANNEL 5
    #define INTAKE_LIMIT_SWITCH_PIN 6

#endif